import './js/querySearchScript';
import './js/trending';
import './js/btnUp';
import './js/footerModal';
import './js/ourTeam';
import './js/pagination';
import './js/trailer';
import './js/movie-modal';
import './js/placeholder-animation';
import './js/pashalka'