import './js/querySearchScript';
import './js/add-to-watched';
import './js/trending';
import './js/btnUp';
import './js/footerModal';
import './js/ourTeam';
import './js/pagination';
import './js/trailer';
import './js/movie-modal';